<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>VhdAttach</RootNamespace>
    <AssemblyName>VhdStudio</AssemblyName>
    <AssemblyTitle>VHD Studio</AssemblyTitle>
    <Description>Attach, maintain and partition VHD, VHDX and ISO images.</Description>
    <ApplicationIcon>Properties\App.ico</ApplicationIcon>
    <ApplicationManifest>Properties\App.manifest</ApplicationManifest>
    <StartupObject>VhdAttach.App</StartupObject>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationVisualStyles>true</ApplicationVisualStyles>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\VhdAttach-Service\FileWithOptions.cs" Link="Shared\FileWithOptions.cs" />
    <Compile Include="..\VhdAttach-Service\ServiceSettings.cs" Link="Shared\ServiceSettings.cs" />
    <Compile Include="..\VhdAttach-Service\Volume.cs" Link="Shared\Volume.cs" />
    <Compile Include="..\VhdAttach-Service\Branding.cs" Link="Shared\Branding.cs" />
    <Compile Include="..\VhdAttach-Service\VirtualDiskImage.cs" Link="Shared\VirtualDiskImage.cs" />
    <Compile Include="..\VhdAttach-Service\VhdxHeader.cs" Link="Shared\VhdxHeader.cs" />
    <Compile Include="..\VhdAttach-Service\(Medo)\VirtualDisk [010].cs" Link="(Medo)\VirtualDisk [010].cs" />
    <Compile Remove="Properties\SolutionInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VhdAttachTest" Key="00240000048000009400000006020000002400005253413100040000010001008f35f900bf246cdcfd0d9eb278b58748591354ee056c42803acb0d99bbaf5e9deb5d995c47d15f925c39be2639210ac76d0417fc658754a432c899f1ddb1ddefa834a314775cf30f4db8739b65777752c700d316daaa43dc3b27c6ca2daa87332f6c6129e4e57f32324839d86a4bb02c9465c4c814a004a1f1b03997473efca8" />
  </ItemGroup>

</Project>
